title: <p align="center"> Aswanth Kumar </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/aswanth-kumar-vusirikala-9b7938163/">LinkedIn</a> |
  <a href="https://github.com/aswanth523/">GitHub</a>
  
  <br>   
  I'm pursuing Executive PG Programme in Machine Learning & AI at Upgrad
  <br>
  </p>



theme: jekyll-theme-minimal
